name: hello-world
on: push
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '5 * * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
